# Travis CI for building ArgumentReader
# --------------------------------------------
language: csharp
solution: ArgumentsExtended.sln
mono: none
dotnet: 3.1.301

addons:
  apt:
    packages:
      - zip

install:
  - dotnet restore

script:
  - dotnet test 

before_deploy:
  - dotnet build -c Release -o ./release
  - dotnet nuget push ./release/GMA.AgrumentsLib.1.0.0.nupkg -k $NUGET_TOKEN -s "https://api.nuget.org/v3/index.json" 
  - dotnet nuget push ./release/GMA.ArgumentMarshalerLib.1.0.0.nupkg -k $NUGET_TOKEN -s "https://api.nuget.org/v3/index.json"
  - zip ArgumentReader.zip ./release/*Lib.dll
  - ls -l ./release

deploy:
  provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN 
  file:
    - "./ArgumentReaderDLL.zip"
    - "./release/ArgumentMarshalerLib.dll"
    - "./release/ArgumentsLib.dll"
    - "./release/BooleanMarshalerLib.dll"
    - "./release/DoubleMarshalerLib.dll"
    - "./release/IntegerMarshalerLib.dll"
    - "./release/StringMarshalerLib.dll"
  skip_cleanup: true
  on:
    tags: true
